### PR TITLE
Rename reactNativeHamsters.podspec to react-native-hamsters.podspec

### PR DESCRIPTION
**Pull request by rossjackson**
The filename `reactNativeHamsters.podspec` is not being respected when installing in my m1 machine using `arch -arm64 pod install`.  Renaming it to the same folder name worked for me.

Error:
```
[!] No podspec found for `react-native-hamsters` in `../node_modules/react-native-hamsters/ios`
```

### CODE REVIEW

**Comment by rossjackson** [comment]
I also tried opening your `example/HamstersJS` folder to make sure its not my setup and I got the same error.  Renaming it worked.  Hopefully, it will work on your end too.

**Comment by austinksmith** [comment]
Thank you @rossjackson , I currently don't have access to a mac to verify this change won't break older versions. I know IOS *was* working before but with the new M1 / M2 line I didn't have a chance to test for those, is there anyway you can verify on your end that it still works for non M1/M2 macbooks ie. x86 not arm64 ? Just want to be safe

**Comment by rossjackson** [comment]
Unfortunately, I don't have an intel based mac :(  I'm not even sure if that is really related to it TBH.  I've seen most podspec filenames have the same name structure as the folder/plugin name.

**Comment by austinksmith** [comment]
@rossjackson alrighty, no worries I'll go ahead and merge your PR into the master branch and push out a new release today. Worse case scenario someone will make another bug report or pr to fix the intel based mac's if they break :)

**Comment by austinksmith** [comment]
@rossjackson I'll have to delay the new version until tomorrow, I'm having issues with my dev environment getting gradle to work properly for some reason (Ubuntu Linux), not related to this pr just my java variables got screwed up during a ruby migration

**Comment by austinksmith** [comment]
@rossjackson the new version is live now, please give it a try on your end, thanks https://www.npmjs.com/package/react-native-hamsters

**Pull request merged**
